### PR TITLE
Added definitions for mySensors 2.0.0

### PR DESCRIPTION
**Pull request by RalfJL**
changed given/when construct to fit Centos 6.7 with perl 5.10

added return queue for controller; now a controller can use mqtt only to control the sensor mesh; no need to talk directly to the gateway
(unfortunately mycontroler is not mature enough yet for this to work, but in preparation)

added queue for messages being sent to a node the next time the node is awake and sends data
node must wait() after the first sent message to receive this message or message may collide or may be lost. Now you can handle actuators without the help of a controler

added ability to assign node id's
now you can live with the gateway and mqtt bus without extra controler

Signed-off-by: RalfJL Ralf@Lehmann.com

### CODE REVIEW

**Comment by Yveaux** [comment]
Could you split it up in small changesets, and refrain from indenting/typographical changes?

**Comment by RalfJL** [comment]
Sorry, this indenting/... is coming from eclipse "autoformat" feature. But I see that it is disturbing and makes it hard to find the real changes.

Over the weekend I will rework that. Is it ok, if I do the following requests?
1. Add definitions to match mySensors 2.0.0
2. Change given/when to make script runable under Centos 6.8 and PERL 5.10
3. Add controler repsonse queue and "delayed response queue"
4. Add simple node id assignment

**Comment by Yveaux** [comment]
Sounds good, although I'd like to see a clear usecase for 'return queue for controller'.

**Comment by RalfJL** [comment]
Currently myController.org is supposed to use 2 queues on mqtt to control the sensor net.
But that does not work with beta 3 (work in progress)
myController.org is supposed to work with serial, ethernet and mqtt.
myController.org was the reason why I came across the second queue 

The third queue is important for me because that enables my home automation, based on openhab, to send events to the nodes. E.g. it can send a shorter interval between transmissions via user variable.
The third queue is most important for nodes that sleep most of the time but still have some configuration or acting capability.

The controller queue could also be used by openhab to turn lights on or dim lights on mysensor nodes
So the "return queue for controller" can also be used for any home automation to send messages to nodes

**Pull request closed without merging**
